# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UpstreamLanduseCalculator
                                 A QGIS plugin
 Calculates land use statistics upstream from a given set of points.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-29
        copyright            : (C) 2025 by The Code Sharman
        email                : michael@thecodesharman.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'The Code Sharman'
__date__ = '2025-11-29'
__copyright__ = '(C) 2025 by The Code Sharman'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UpstreamLanduseCalculator class from file UpstreamLanduseCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .upstream_landuse_calculator import UpstreamLanduseCalculatorPlugin
    return UpstreamLanduseCalculatorPlugin()
