# -*- coding: utf-8 -*-

"""
/***************************************************************************
 UpstreamLanduseCalculator
                                 A QGIS plugin
 Calculates land use statistics upstream from a given set of points.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-29
        copyright            : (C) 2025 by The Code Sharman
        email                : michael@thecodesharman.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'The Code Sharman'
__date__ = '2025-11-29'
__copyright__ = '(C) 2025 by The Code Sharman'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
import os

from qgis.core import QgsProcessingProvider, QgsProcessingModelAlgorithm

from .alum_code_level_algorithm import AlumCodeLevelAlgorithm
from .upstream_catchment_algorithm import UpstreamCatchmentAlgorithm
from .reproject_to_match_algorithm import ReprojectToMatchAlgorithm

class UpstreamLanduseCalculatorProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadModel(self, name):
        model_path = os.path.join(os.path.dirname(__file__), 'models', name)
        model = QgsProcessingModelAlgorithm()
        model.fromFile(model_path)
        self.addAlgorithm(model)

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(UpstreamCatchmentAlgorithm())
        self.addAlgorithm(ReprojectToMatchAlgorithm())
        self.addAlgorithm(AlumCodeLevelAlgorithm())
        self.loadModel('upstream_landuse.model3')

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'UpstreamLanduseProvider'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('Upstream Landuse Calculator')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QgsProcessingProvider.icon(self)

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
